"""State machines and closed vocabularies. Pure: stdlib only.

User-facing uncertainty states are uppercase per CONTEXT.md.
"""

from __future__ import annotations

from enum import StrEnum


class JobStatus(StrEnum):
    PENDING = "PENDING"
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DUPLICATE_SUPPRESSED = "DUPLICATE_SUPPRESSED"
    NOT_PUBLISHED = "NOT_PUBLISHED"
    NO_ACTION = "NO_ACTION"
    EXTRACTION_REJECTED = "EXTRACTION_REJECTED"


class ArtifactAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    NOT_PUBLISHED = "NOT_PUBLISHED"
    RETRIEVAL_FAILED = "RETRIEVAL_FAILED"


class AnchorType(StrEnum):
    PAGE = "page"
    TABLE_CELL = "table_cell"
    DATASET_ROW = "dataset_row"
    TRANSCRIPT_TIME = "transcript_time"
    VIDEO_TIME = "video_time"
    MAP_FEATURE = "map_feature"


class EvidenceObjectType(StrEnum):
    COMMITMENT = "COMMITMENT"
    DECISION = "DECISION"
    ACTION_ITEM = "ACTION_ITEM"
    VOTE = "VOTE"
    CLAIM = "CLAIM"
    UNKNOWN = "UNKNOWN"


class EvidenceStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"
    NOT_PUBLISHED = "NOT_PUBLISHED"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class LinkStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    CANDIDATE = "CANDIDATE"
    REJECTED = "REJECTED"


class DeltaCategory(StrEnum):
    ADVANCED = "ADVANCED"
    REVISED = "REVISED"
    DEFERRED = "DEFERRED"
    CONFLICTING = "CONFLICTING"
    EXPECTED_EVIDENCE_ARRIVED = "EXPECTED_EVIDENCE_ARRIVED"
    RECORD_GAP = "RECORD_GAP"


class ReviewOutcome(StrEnum):
    APPROVE = "APPROVE"
    REVISE = "REVISE"
    REJECT = "REJECT"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class LedgerEventType(StrEnum):
    ARTIFACT_STORED = "ARTIFACT_STORED"
    ARTIFACT_NOT_PUBLISHED = "ARTIFACT_NOT_PUBLISHED"
    EVIDENCE_ACCEPTED = "EVIDENCE_ACCEPTED"
    ENTITY_LINKED = "ENTITY_LINKED"
    EXTRACTION_REJECTED = "EXTRACTION_REJECTED"
    NO_MATERIAL_DELTA = "NO_MATERIAL_DELTA"
    DELTA_PROPOSED = "DELTA_PROPOSED"
    DELTA_REJECTED = "DELTA_REJECTED"
    DELTA_STAGED = "DELTA_STAGED"
    CASE_HUMAN_REVIEW = "CASE_HUMAN_REVIEW"
    INQUIRY_STAGED = "INQUIRY_STAGED"
    INQUIRY_REJECTED = "INQUIRY_REJECTED"
    INQUIRY_APPROVAL_ISSUED = "INQUIRY_APPROVAL_ISSUED"
    INQUIRY_APPROVAL_REJECTED = "INQUIRY_APPROVAL_REJECTED"
    APPROVAL_REFUSED = "APPROVAL_REFUSED"
    PACKET_RENDERED = "PACKET_RENDERED"


class InquiryType(StrEnum):
    """Design doc §17: the only research actions the planner may draft. Never a send."""

    SOURCE_QUESTION = "SOURCE_QUESTION"
    RECORDS_REQUEST_OUTLINE = "RECORDS_REQUEST_OUTLINE"
    WATCH_REMINDER = "WATCH_REMINDER"
    HUMAN_RESEARCH_TASK = "HUMAN_RESEARCH_TASK"


class ApprovalActionType(StrEnum):
    """The only external-facing action a token can authorize today."""

    RENDER_INQUIRY_PACKET = "RENDER_INQUIRY_PACKET"


class DeltaResultType(StrEnum):
    DECISION_DELTA = "DECISION_DELTA"
    NO_MATERIAL_DELTA = "NO_MATERIAL_DELTA"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class Materiality(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
